# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  ENV['ANSIBLE_ROLES_PATH'] = "../../ansible/roles"
  config.vm.box = "centos/7"

  (1..2).each do |cnt|
    config.vm.define "logserver#{cnt}" do |server|
      server.vm.hostname = "logserver#{cnt}.local"
      server.vm.synced_folder ".", "/vagrant", disabled: true
      server.vm.network :forwarded_port, id: "ssh", guest: 22, host: "221#{cnt}"
      server.vm.network :private_network, ip: "192.168.22.1#{cnt}"

      if cnt == 2
        config.vm.provision "ansible" do |ansible|
         ansible.playbook = "../../ansible/playbooks/log_aggregate.yml"
         ansible.inventory_path = "../../ansible/inventory/hostlist"
         ansible.limit = 'logserver'
        end
      end
    end
  end

  config.vm.define "logclient1" do |server|
    server.vm.hostname = "logclient1.local"
    server.vm.synced_folder ".", "/vagrant", disabled: true
    server.vm.network :forwarded_port, id: "ssh", guest: 22, host: "2221"
    server.vm.network :private_network, ip: "192.168.22.21"

    config.vm.provision "ansible" do |ansible|
     ansible.playbook = "../../ansible/playbooks/log_aggregate.yml"
     ansible.inventory_path = "../../ansible/inventory/hostlist"
     ansible.limit = 'logclient'
    end
  end
end
