# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  ENV['ANSIBLE_ROLES_PATH'] = "../../ansible/roles"
  config.vm.box = "centos/7"

  (1..3).each do |cnt|
    config.vm.define "percona#{cnt}" do |server|
      server.vm.hostname = "percona#{cnt}.local"
      server.vm.synced_folder ".", "/vagrant", disabled: true
      server.vm.network :forwarded_port, id: "ssh", guest: 22, host: "222#{cnt}"
      server.vm.network :forwarded_port, id: "mysql", guest: 3306, host: "3306#{cnt}"
      server.vm.network :private_network, ip: "192.168.22.1#{cnt}"
      server.vm.network :private_network, ip: "192.168.1.1#{cnt}", virtualbox__intnet: "test_net1"

      if cnt == 3
        config.vm.provision "ansible" do |ansible|
         ansible.playbook = "../../ansible/playbooks/percona_cluster.yml"
         ansible.inventory_path = "../../ansible/inventory/hostlist"
         ansible.limit = 'percona_cluster'
        end
      end
    end
  end
end
