FROM python:3.7

RUN groupadd -r uwsgi && useradd -r -g uwsgi uwsgi
#RUN pip install Flask==1.0.2
#RUN pip install Flask==1.0.2 uWSGI==2.0.17
RUN pip install Flask==1.0.2 uWSGI==2.0.17 requests==2.5.1 redis==2.10.6
WORKDIR /app
COPY app /app
COPY cmd.sh /

EXPOSE 9090 9191
USER uwsgi

#CMD ["python", "identidock.py"]
#CMD ["uwsgi", "--http", "0.0.0.0:9090", "--wsgi-file", "/app/identidock.py", \
#     "--callable", "app", "--stats", "0.0.0.0:9191"]
CMD ["/cmd.sh"]
