# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  ENV['ANSIBLE_ROLES_PATH'] = "../../ansible/roles"

  config.vm.define "zabbix_server" do |clm|
    clm.vm.box = "centos/7"
    clm.vm.hostname = "zabbix01.local"
    clm.vm.synced_folder ".", "/vagrant", disabled: true
    clm.vm.network :forwarded_port, id: "ssh", guest: 22, host: "2221"
    clm.vm.network :forwarded_port, id: "zabbix", guest: 80, host: "8080"
    clm.vm.network :private_network, ip: "192.168.33.11"

    clm.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../ansible/playbooks/zabbix.yml"
      ansible.inventory_path = "../../ansible/inventory/hostlist"
      ansible.limit = 'zabbix01'
    end
  end
end
